apiVersion: v1
kind: Pod
metadata:
  name: volumes-demo
  labels:
    app: nginx
spec:
  initContainers:
  - image: busybox
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 100m
        memory: 100Mi
    args:
    - /bin/sh
    - -c
    - 'printf "<h1>VolumeFile</h1>\n<p>This is a custom page</p>\n" > /mnt/vol/html/page1.html'
    name: initialiser
    volumeMounts:
    - mountPath: /mnt/vol/html
      name: demo-volume
  containers:
  - image: nginx:1.20-alpine
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 100m
        memory: 100Mi
    name: nginx-server
    volumeMounts:
    - mountPath: /usr/share/nginx/html/custom
      name: demo-volume
    ports:
    - containerPort: 80
  volumes:
  - name: demo-volume
    emptyDir: {}
