kind: PersistentVolume
apiVersion: v1
metadata:
  name: 2gpv
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    type: DirectoryOrCreate
    path: /var/volumes/data01
