apiVersion: v1
kind: Pod
metadata:
  labels:
    run: secrets
  name: secrets
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - 'sleep 1d'
    image: busybox
    name: secrets 
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysql
          key: password
    - name: MYSQL_USER
      valueFrom:
        secretKeyRef:
          name: mysql
          key: user
