apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: secretm
  name: secretm
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - 'sleep 1d'
    image: busybox
    name: secretm
    volumeMounts:
    - mountPath: /mysql
      name: mysql
  volumes:
  - name: mysql
    secret:
      secretName: mysql
