apiVersion: v1
kind: Secret
metadata:
  name: example-secret
stringData:
  TOKEN_ID: AAAAA32TGFVWG4TKACMLWI
  TOKEN: fbQ34tqwegrgAXeRg9ervjwcJoK2ebfqmcwirbfwefw33r040fmwjd923ie2FNiwdalnve3igb3erfqcmne16eubgiewfj77erifwnvwbfb3rhwf