apiVersion: v1
kind: Namespace
metadata:
  name: low-usage-limit
---
apiVersion: v1
kind: LimitRange
metadata:
  namespace: low-usage-limit
  name: low-resource-range
spec:
  limits:
  - default:
      cpu: 1
      memory: 500Mi
    defaultRequest:
      cpu: 0.5
      memory: 100Mi
    type: Container
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: limited-hog
  name: limited-hog
  namespace: low-usage-limit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: limited-hog
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: limited-hog
    spec:
      containers:
      - image: vish/stress
        name: limited-hog
        args:
        - -cpus
        - "2"
        - -mem-total
        - "950Mi"
        - -mem-alloc-size
        - "100Mi"
        - -mem-alloc-sleep
        - "1s"