apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: limited-hog
  name: limited-hog
  namespace: low-usage-limit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: limited-hog
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: limited-hog
    spec:
      containers:
      - image: vish/stress
        name: limited-hog
        resources:
          limits:
            cpu: "1"
            memory: "4Gi"
          requests:
            cpu: "0.5"
            memory: "500Mi"
        args:
        - -cpus
        - "2"
        - -mem-total
        - "950Mi"
        - -mem-alloc-size
        - "100Mi"
        - -mem-alloc-sleep
        - "1s"