apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: simple-app
  name: simple-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: simple-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0%
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: simple-app
    spec:
      containers:
      - image: danielives/helloworld:v2
        name: simple-app
        resources: {}
