apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: simple-app
  name: simple-app
spec:
  selector:
    matchLabels:
      app: simple-app
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: simple-app
    spec:
      containers:
      - image: danielives/simple-app:v1
        name: simple-app
        resources: {}
