apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-logger
spec:
  selector:
    matchLabels:
      system: DaemonSetOne
  template:
    metadata:
      labels:
        system: DaemonSetOne
    spec:
      containers:
      - name: logger
        image: busybox
        volumeMounts:
        - name: logs
          mountPath: /logs
        command:
        - /bin/sh
        - -c
        - "tail -f /logs/syslog"
      volumes:
      - name: logs
        hostPath:
          type: Directory
          path: /var/log
