apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: simple-app
  name: simple-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: simple-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: simple-app
    spec:
      containers:
      - image: danielives/simple-app:v2
        name: simple-app
