apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: simple-app
  name: simple-app
spec:
  replicas: 4
  serviceName: stateful-simple-app
  selector:
    matchLabels:
      app: simple-app
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: simple-app
    spec:
      containers:
      - image: busybox
        name: simple-app
        resources: {}
        args: [/bin/sh, -c, 'sleep infinity']
