apiVersion: v1
kind: Pod
metadata:
  labels:
    app: myapp
  name: myapp
spec:
  nodeSelector:
    highmem: true
  containers:
  - image: danielives/simple-app:v1
    name: myapp
    imagePullPolicy: IfNotPresent
    ports:
      - containerPort: 80
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
