apiVersion: kubescheduler.config.k8s.io/v1
kind: KubeSchedulerConfiguration
profiles:
  - schedulerName: default-scheduler
  - schedulerName: only-soft-taints
    plugins:
      filter:
        disabled:
        - name: TaintToleration
