apiVersion: v1
kind: Pod
metadata:
  labels:
    app: myapp
  name: myapp
spec:
  containers:
  - image: danielives/simple-app:v1
    name: myapp
    imagePullPolicy: IfNotPresent
    ports:
      - containerPort: 8080
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
  tolerations:
  - key: status
    operator: Equal
    value: flaky
    effect: NoExecute
    tolerationSeconds: 15
