apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: web
  name: web
spec:
  containers:
  - image: httpd
    name: web
    resources: {}
    ports:
      containerPort: 80
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
