apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
  - image: alpine/kubectl
    name: secret-getter
    command:
      - kubectl
      - get
      - secret/lfsecret
      - -ojson
  restartPolicy: Never
  terminationGracePeriodSeconds: 0
