apiVersion: v1
kind: Service
metadata:
  labels:
    app: myapp
    version: v1
  name: myapp
  namespace: ts-demo
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: myapp
    version: v1
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myapp
    version: v1
  name: myapp
  namespace: ts-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
      version: v1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: myapp
        version: v1
    spec:
      containers:
      - image: danielives/simple-app:v1
        imagePullPolicy: IfNotPresent
        name: myapp
        ports: [containerPort: 80]
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
