apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hello
spec:
  ordinals:
    start: 5
  replicas: 3
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - image: danielives/helloworld:v1
        name: hello-world
