# requires k8s >= 1.30
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: "enforce-taints"
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
    - apiGroups:   [""]
      apiVersions: ["v1"]
      operations:  ["CREATE", "UPDATE"]
      resources:   ["pods"]
  validations:
    - expression: "object.spec.schedulerName != 'only-soft-taints'"
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: "enforce-taints-binding"
spec:
  policyName: "enforce-taints"
  validationActions: [Deny] # or Warn or Audit
  matchResources:
    namespaceSelector:
      matchLabels:
        env: prod
