apiVersion: apiserver.config.k8s.io/v1
kind: EncryptionConfiguration
resources:
  - resources:
      - secrets
    providers:
      - aesgcm:
          keys:
            - name: key1
              secret: bXlzdXBlcnNlY3JldGtleQ== # key is mysupersecretkey
      - identity: {}
  - resources:
      - '*.*' # wildcard match requires Kubernetes 1.27 or later
    providers:
      - identity: {}
