apiVersion: apps/v1
kind: deployment
metadata:
  labels:
    app: dodgy
  name: dodgy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dodgy
  strategy: {}
  template:
    metadata:
      labels:
        app: dodgy
    spec:
      containers:
      - image: ngnix
        name: nginx
        volumeMounts:
        - mountPath: /etc/nginx
          name: nginx-conf
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 500Mi
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx
