apiVersion: v1
data:
  nginx.conf: |
    events {}

    http {
      server {
        listen 80;

        location =/health {
          return 500 OOPS;
        }
      }
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: nginx
