apiVersion: v1
kind: Pod
metadata:
  labels:
    app: myapp2
  name: myapp2
spec:
  containers:
  - image: danielives/simple-app:v2
    name: myapp
    imagePullPolicy: Always
    ports:
      - containerPort: 8080
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
