apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: dev-cluster
  region: eu-west-2
  version: "1.22"
availabilityZones:
  - eu-west-2a
  - eu-west-2b
  - eu-west-2c
vpc:
  clusterEndpoints:
    publicAccess: true
    privateAccess: true
managedNodeGroups:
  - name: dev-nodes
    instanceType: t3.small
    desiredCapacity: 2
    minSize: 1
    maxSize: 4
    ssh:
      enableSsm: true
