#!/bin/bash
. ../demo-magic.sh
clear

pe "kubectl create deploy webservers --image=httpd --port=80 --replicas=3"
# pe "kubectl scale deploy myapp --replicas=3"
pe "kubectl get po -o wide"
pe "kubectl expose deploy webservers"
pe "kubectl get svc webservers"
# pe 'IP=$(kubectl get svc webservers --no-headers -o=custom-columns=ip:.spec.clusterIP)'
# pe 'curl -w "\n" $IP'
pe "kubectl get ep"
pe "kubectl run tmp01 --image=tutum/dnsutils -- sleep infinity"
pei "kubectl wait --for=condition=ready pod tmp01"
pe "kubectl exec -it tmp01 -- nslookup webservers"
pe "kubectl delete svc webservers"
pe "kubectl expose deploy webservers --type=NodePort"
pe "kubectl get svc webservers"
pe "kubectl exec -it tmp01 -- nslookup webservers"
pe 'PORT=$(kubectl get svc webservers -o=custom-columns=ip:.spec.ports[0].nodePort --no-headers)'
pe 'echo $PORT'
pe 'curl -w "\n" localhost:$PORT'
pe "kubectl get ep"
pe "kubectl delete svc webservers"
pe "kubectl expose deploy webservers --type=LoadBalancer"
pe "kubectl get svc webservers"
pe "kubectl exec -it tmp01 -- nslookup webservers"
pe "sleep 5"
pe "kubectl get svc webservers"
pe "kubectl delete deploy webservers"
pei "kubectl delete svc webservers"
pei "kubectl delete pod tmp01"