apiVersion: batch/v1
kind: Job
metadata:
  name: somejob
spec:
  template:
    spec:
      containers:
      - image: busybox
        name: somejob
        args:
          - /bin/sh
          - -c
          - 'echo hello world; sleep 30; echo byee!'
      restartPolicy: Never
