apiVersion: v1
kind: ConfigMap
metadata:
  name: test-script
data:
  test.sh: |
    lines=$(kubectl get pods --selector=immune!=true \
      --output go-template --template \
      '{{range .items}}{{.metadata.name}} {{.metadata.creationTimestamp}} {{.metadata.namespace}}{{"\n"}}{{end}}' | \
      awk '$2 <= "'$(date -d 'now-5 days' -Ins --utc | sed 's/+0000/Z/')'" { print $1 " " $3}')
    #echo $lines
    array=($lines)
    for((n=0;n<${#array[@]};n+=2)); do kubectl delete pod ${array[n]} -n ${array[n+1]}; done
---
apiVersion: v1
kind: ServiceAccount
metadata:.
  name: euthanasia-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: delete-pods
rules:
  - apiGroups: [""]
    resources:
      - pods
    verbs:
      - get
      - list
      - delete 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: delete-pods-to-sa
subjects:
  - kind: ServiceAccount
    name: euthanasia-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: delete-pods
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: test
spec:
  jobTemplate:
    metadata:
      name: test
    spec:
      template:
        spec:
          serviceAccountName: euthanasia-sa
          volumes:
          - name: test-script
            configMap:
              name: test-script
              defaultMode: 0777
          containers:
          - command:
            - bin/bash
            args:
            - -c
            - /test-script/test.sh
            image: bitnami/kubectl:1.23
            name: locust
            volumeMounts:
              - mountPath: /test-script
                name: test-script
          restartPolicy: Never
  schedule: '* * * * *' # once per minute (for demo purposes)
