apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nip
  # annotations:
  #   kubernetes.io/ingress.class: nginx
  namespace: default
spec:
  ingressClassName: nginx
  rules:
    - host: internal.13.40.132.39.nip.io
      http:
        paths:
          - backend:
              service:
                name: web-two
                port:
                  number: 80
            path: /
            pathType: ImplementationSpecific
    - host: external.13.40.132.39.nip.io
      http:
        paths:
          - backend:
              service:
                name: web-one
                port:
                  number: 80
            path: /
            pathType: ImplementationSpecific
    - host: dash.13.40.132.39.nip.io
      http:
        paths:
          - backend:
              service:
                name: kubernetes-dashboard
                port:
                  number: 443
            path: /
            pathType: ImplementationSpecific
status:
  loadBalancer: {}
